# Generates lib/regexp/re_uniprop.h: the Unicode properties `\p{...}` can name.
# Run it under a CRuby whose Unicode data is the one you want:
#
#   ruby tools/gen_re_uniprop.rb > lib/regexp/re_uniprop.h
#
# The rest of lib/regexp (the engine, re_ctype.h, the case tables) is mruby's
# and is taken by copying it; this table is spinel's own, for the `\p{...}`
# rewrite in re_spinel.c. Read off CRuby rather than off the Unicode Character
# Database: what this has to agree with is CRuby, so asking CRuby is both
# shorter and closer to the question.
#
# Two tables, because the properties fall into two shapes.
#
# GENERAL CATEGORY is a partition -- every codepoint has exactly one -- so it
# is one run table rather than thirty range lists: the codepoint a run starts
# at in the high 21 bits, its category in the low 6. One binary search answers
# `\p{Lu}` and `\p{L}` alike, the second by comparing only the first letter.
# Thirty lists would have cost 5,752 runs between them; the partition costs
# what its boundaries cost.
#
# EMOJI properties are not a partition and overlap each other, so they get a
# bitmask run table of their own -- the same encoding the ctype table uses.
#
# The POSIX-named properties (`\p{Alpha}`, `\p{Word}`, ...) are NOT here: they
# are the types re_ctype.h already carries, and the compiler routes them to it.
# That is not only smaller, it is what makes them fold correctly under /i.

GC = %w[Lu Ll Lt Lm Lo Mn Mc Me Nd Nl No Pc Pd Ps Pe Pi Pf Po
        Sm Sc Sk So Zs Zl Zp Cc Cf Co Cs Cn]
EMOJI = ["Emoji", "Emoji_Presentation", "Extended_Pictographic"]

MAX = 0x10FFFF
SURROGATE = 0xD800..0xDFFF

def chr_of(cp)
  return nil if SURROGATE.cover?(cp)
  begin
    cp.chr(Encoding::UTF_8)
  rescue RangeError
    nil
  end
end

$stderr.puts "scanning general categories..."
gc_re = GC.map { |n| [n, Regexp.new("\\p{#{n}}")] }
# Cn (unassigned) is the fallback: a codepoint no other category claims.
gc_of = Array.new(MAX + 1, GC.index("Cn"))
(0..MAX).each do |cp|
  ch = chr_of(cp)
  next if ch.nil?
  gc_re.each_with_index do |(_n, re), i|
    if re.match?(ch)
      gc_of[cp] = i
      break
    end
  end
  $stderr.print "." if (cp & 0xFFFF).zero?
end
$stderr.puts

$stderr.puts "scanning emoji properties..."
emoji_re = EMOJI.map { |n| Regexp.new("\\p{#{n}}") }
emoji_of = Array.new(MAX + 1, 0)
(0..MAX).each do |cp|
  ch = chr_of(cp)
  next if ch.nil?
  m = 0
  emoji_re.each_with_index { |re, i| m |= (1 << i) if re.match?(ch) }
  emoji_of[cp] = m
end

# Compress an array of small values into ascending runs of (start, value).
def runs(values)
  out = []
  prev = nil
  values.each_with_index do |v, cp|
    if v != prev
      out << [cp, v]
      prev = v
    end
  end
  out
end

gc_runs = runs(gc_of)
emoji_runs = runs(emoji_of)

puts "/* Generated by tools/gen_re_uniprop.rb -- do not edit."
puts "   The Unicode properties `\\p{...}` names, in #{gc_runs.size} category runs"
puts "   and #{emoji_runs.size} emoji runs."
puts "   Source: CRuby #{RUBY_VERSION}'s Unicode data."
puts
puts "   The POSIX-named properties are not here: they are what re_ctype.h"
puts "   already carries, and the compiler routes them to it. */"
puts
puts "#ifndef RE_UNIPROP_H"
puts "#define RE_UNIPROP_H"
puts
puts "/* General category ids, in the order the table encodes them. */"
puts "enum {"
GC.each_with_index { |n, i| puts "  RE_GC_#{n.upcase} = #{i}," }
puts "  RE_GC_COUNT = #{GC.size}"
puts "};"
puts
puts "static const char *const re_gc_names[#{GC.size}] = {"
puts "  " + GC.map { |n| "\"#{n}\"" }.join(", ")
puts "};"
puts
puts "/* One run: the codepoint it starts at in the high 21 bits, its general"
puts "   category in the low 6. Ascending; a run ends where the next begins,"
puts "   and the last at U+10FFFF. */"
puts "#define RE_GC_RUN_START(e) ((uint32_t)((e) >> 6))"
puts "#define RE_GC_RUN_CAT(e)   ((uint32_t)((e) & 0x3F))"
puts "#define RE_GC_RUNS #{gc_runs.size}"
puts "static const uint32_t re_gc_table[#{gc_runs.size}] = {"
gc_runs.each_slice(8) do |slice|
  puts "  " + slice.map { |(cp, v)| format("0x%08X", (cp << 6) | v) }.join(", ") + ","
end
puts "};"
puts
puts "/* The emoji properties overlap, so a run carries a set. */"
EMOJI.each_with_index { |n, i| puts "#define RE_EMOJI_#{n.upcase} 0x#{(1 << i).to_s(16)}" }
puts "#define RE_EMOJI_RUN_START(e) ((uint32_t)((e) >> 3))"
puts "#define RE_EMOJI_RUN_SET(e)   ((uint32_t)((e) & 0x7))"
puts "#define RE_EMOJI_RUNS #{emoji_runs.size}"
puts "static const uint32_t re_emoji_table[#{emoji_runs.size}] = {"
emoji_runs.each_slice(8) do |slice|
  puts "  " + slice.map { |(cp, v)| format("0x%08X", (cp << 3) | v) }.join(", ") + ","
end
puts "};"
puts
puts "#endif /* RE_UNIPROP_H */"
